-- drop the database table
drop table if exists contacts;

-- create the table contacts
create table contacts (
	id INT primary key auto_increment,
	firstname VARCHAR(50) not null,
	lastname VARCHAR(50),
	gender VARCHAR(50),
	email VARCHAR(255) not null unique,
	phone VARCHAR(50) not null unique,
	city VARCHAR(50),
	state VARCHAR(50),
	country VARCHAR(50),
	picture VARCHAR(255)
);

-- insert 100 rows
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (1, 'Marisa', 'Kinzel', 'Female', 'mkinzel0@cbsnews.com', '5187050786', 'Albany', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/1.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (2, 'Alford', 'Antosch', 'Male', 'aantosch1@paypal.com', '5169050182', 'Port Washington', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/2.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (3, 'Edi', 'Rooney', 'Female', 'erooney2@surveymonkey.com', '7345773914', 'Ann Arbor', 'Michigan', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/3.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (4, 'Saundra', 'M''Chirrie', 'Female', 'smchirrie3@wufoo.com', '5711736975', 'Ashburn', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/4.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (5, 'Lacie', 'Eastridge', 'Female', 'leastridge4@usatoday.com', '2175697547', 'Springfield', 'Illinois', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/5.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (6, 'Amalie', 'Urrey', 'Female', 'aurrey5@privacy.gov.au', '5059226814', 'Santa Fe', 'New Mexico', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/6.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (7, 'Natka', 'Rowter', 'Female', 'nrowter6@ezinearticles.com', '2165876637', 'Cleveland', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/7.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (8, 'Carolina', 'Denisot', 'Female', 'cdenisot7@google.com', '3309863964', 'Akron', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/8.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (9, 'Millie', 'Joyce', 'Female', 'mjoyce8@wikia.com', '2092955202', 'Modesto', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/9.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (10, 'Harlen', 'Handley', 'Male', 'hhandley9@tripadvisor.com', '5706989531', 'Scranton', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/10.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (11, 'Winifield', 'Eymer', 'Male', 'weymera@bloglines.com', '6265130728', 'Pasadena', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/11.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (12, 'Stoddard', 'Fleckno', 'Female', 'sflecknob@biglobe.ne.jp', '7186304108', 'Flushing', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/12.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (13, 'Jacobo', 'Larose', 'Male', 'jlarosec@buzzfeed.com', '4129516395', 'Pittsburgh', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/13.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (14, 'Oberon', 'Scramage', 'Male', 'oscramaged@tamu.edu', '5404519801', 'Roanoke', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/14.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (15, 'Constantine', 'Chestney', 'Male', 'cchestneye@oaic.gov.au', '2056475251', 'Birmingham', 'Alabama', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/15.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (16, 'Kipp', 'Kail', 'Female', 'kkailf@soundcloud.com', '8138813023', 'Tampa', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/16.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (17, 'Karoline', 'Chappel', 'Female', 'kchappelg@guardian.co.uk', '7149062920', 'Garden Grove', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/17.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (18, 'Netta', 'Gainor', 'Female', 'ngainorh@wp.com', '8168075932', 'Kansas City', 'Missouri', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/18.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (19, 'Cordelie', 'Bichard', 'Female', 'cbichardi@seesaa.net', '8182540229', 'North Hollywood', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/19.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (20, 'Anne-corinne', 'Coultard', 'Female', 'acoultardj@newsvine.com', '2485585260', 'Southfield', 'Michigan', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/20.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (21, 'Jefferson', 'Laffan', 'Male', 'jlaffank@loc.gov', '3233031106', 'Los Angeles', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/21.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (22, 'Cahra', 'Ferby', 'Female', 'cferbyl@hostgator.com', '9136303350', 'Shawnee Mission', 'Kansas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/22.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (23, 'Pepi', 'Ingliss', 'Female', 'pinglissm@toplist.cz', '3148625473', 'Saint Louis', 'Missouri', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/23.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (24, 'Raddie', 'Pepys', 'Male', 'rpepysn@cnn.com', '2145542536', 'Dallas', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/24.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (25, 'Carmina', 'Winder', 'Female', 'cwindero@walmart.com', '5109424650', 'Berkeley', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/25.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (26, 'Maryanne', 'Yukhnov', 'Female', 'myukhnovp@bravesites.com', '4342634901', 'Lynchburg', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/26.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (27, 'Roderick', 'Connachan', 'Male', 'rconnachanq@spiegel.de', '7146886941', 'Anaheim', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/27.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (28, 'Geri', 'Perez', 'Female', 'gperezr@adobe.com', '7026126873', 'Las Vegas', 'Nevada', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/28.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (29, 'Mel', 'Baltzar', 'Female', 'mbaltzars@nature.com', '5596519032', 'Fresno', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/29.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (30, 'Alisa', 'Dobbing', 'Female', 'adobbingt@wordpress.org', '3059173006', 'Miami', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/30.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (31, 'Salem', 'Beggin', 'Male', 'sbegginu@qq.com', '4128696645', 'Pittsburgh', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/31.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (32, 'Tabatha', 'Filyushkin', 'Female', 'tfilyushkinv@about.me', '8038762272', 'Columbia', 'South Carolina', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/32.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (33, 'Joela', 'Kervin', 'Female', 'jkervinw@virginia.edu', '6075975147', 'Elmira', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/33.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (34, 'Renelle', 'Inglesant', 'Female', 'ringlesantx@illinois.edu', '6263724985', 'Pasadena', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/34.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (35, 'Dunc', 'Geffe', 'Male', 'dgeffey@goo.gl', '5104620066', 'Berkeley', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/35.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (36, 'Ty', 'Castagna', 'Male', 'tcastagnaz@exblog.jp', '2123819581', 'New York City', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/36.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (37, 'Johannah', 'Alten', 'Female', 'jalten10@toplist.cz', '8016541123', 'Salt Lake City', 'Utah', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/37.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (38, 'Judith', 'Rigate', 'Female', 'jrigate11@nyu.edu', '7316292644', 'Jackson', 'Tennessee', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/38.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (39, 'Brig', 'Gretton', 'Male', 'bgretton12@360.cn', '5163783420', 'Great Neck', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/39.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (40, 'Demetris', 'Crass', 'Male', 'dcrass13@nature.com', '5096468625', 'Yakima', 'Washington', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/40.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (41, 'Kimberley', 'Clowser', 'Female', 'kclowser14@dailymotion.com', '3055298886', 'Miami', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/41.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (42, 'Kellina', 'Laborda', 'Female', 'klaborda15@hexun.com', '5131506496', 'Cincinnati', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/42.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (43, 'Mendie', 'Pursey', 'Male', 'mpursey16@xrea.com', '2025913549', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/43.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (44, 'Alexa', 'Fawcitt', 'Female', 'afawcitt17@devhub.com', '4136046919', 'Springfield', 'Massachusetts', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/44.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (45, 'Levi', 'Toplin', 'Male', 'ltoplin18@irs.gov', '8329736360', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/45.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (46, 'Broderick', 'Shields', 'Male', 'bshields19@google.com', '3046631322', 'Huntington', 'West Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/46.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (47, 'Carlos', 'McKeating', 'Male', 'cmckeating1a@clickbank.net', '7024519935', 'Las Vegas', 'Nevada', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/47.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (48, 'Iggy', 'Paybody', 'Male', 'ipaybody1b@army.mil', '9042689454', 'Jacksonville', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/48.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (49, 'Bennie', 'Edser', 'Male', 'bedser1c@si.edu', '3474276748', 'Brooklyn', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/49.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (50, 'Janaya', 'Ricker', 'Female', 'jricker1d@virginia.edu', '9169398918', 'Sacramento', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/50.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (51, 'Dix', 'Kynge', 'Female', 'dkynge1e@fc2.com', '2058742882', 'Birmingham', 'Alabama', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/51.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (52, 'Vanya', 'Jacqueminot', 'Male', 'vjacqueminot1f@nyu.edu', '2811888943', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/52.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (53, 'Norrie', 'Dalgliesh', 'Male', 'ndalgliesh1g@cnn.com', '4044725248', 'Atlanta', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/53.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (54, 'Reagan', 'Benoy', 'Male', 'rbenoy1h@hubpages.com', '2129391526', 'New York City', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/54.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (55, 'Westbrook', 'Older', 'Male', 'wolder1i@multiply.com', '3379619719', 'Lake Charles', 'Louisiana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/55.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (56, 'Salomon', 'Tincey', 'Male', 'stincey1j@live.com', '7075809911', 'Petaluma', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/56.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (57, 'Far', 'Tribell', 'Male', 'ftribell1k@cargocollective.com', '3124182328', 'Chicago', 'Illinois', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/57.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (58, 'Berny', 'Nolan', 'Female', 'bnolan1l@vkontakte.ru', '7145157104', 'Irvine', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/58.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (59, 'Bertha', 'Crang', 'Female', 'bcrang1m@51.la', '9529102827', 'Young America', 'Minnesota', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/59.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (60, 'Goddart', 'Ragdale', 'Male', 'gragdale1n@globo.com', '5736625739', 'Columbia', 'Missouri', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/60.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (61, 'Odo', 'Coffey', 'Male', 'ocoffey1o@google.cn', '4056825612', 'Oklahoma City', 'Oklahoma', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/61.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (62, 'Duane', 'Dumbare', 'Male', 'ddumbare1p@goodreads.com', '7017621138', 'Fargo', 'North Dakota', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/62.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (63, 'Merrily', 'Gemelli', 'Female', 'mgemelli1q@virginia.edu', '3369408326', 'Winston Salem', 'North Carolina', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/63.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (64, 'Isaac', 'Baum', 'Male', 'ibaum1r@chronoengine.com', '8136860844', 'Tampa', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/64.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (65, 'Jacqueline', 'Dunham', 'Female', 'jdunham1s@oakley.com', '7857327203', 'Topeka', 'Kansas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/65.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (66, 'Rene', 'Roblin', 'Male', 'rroblin1t@bloomberg.com', '8014958722', 'Sandy', 'Utah', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/66.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (67, 'Nico', 'McCloughen', 'Male', 'nmccloughen1u@ed.gov', '2022907946', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/67.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (68, 'Gonzales', 'Seymour', 'Male', 'gseymour1v@sina.com.cn', '3043442694', 'Charleston', 'West Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/68.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (69, 'Kevon', 'Willars', 'Male', 'kwillars1w@narod.ru', '6197397645', 'San Diego', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/69.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (70, 'Augusta', 'Mc-Kerley', 'Female', 'amckerley1x@reuters.com', '5025978380', 'Louisville', 'Kentucky', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/70.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (71, 'Ferris', 'Iveson', 'Male', 'fiveson1y@clickbank.net', '5017890236', 'Little Rock', 'Arkansas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/71.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (72, 'Nickie', 'Kienle', 'Male', 'nkienle1z@t.co', '3199320114', 'Iowa City', 'Iowa', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/72.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (73, 'Reina', 'Maffiotti', 'Female', 'rmaffiotti20@homestead.com', '4802081632', 'Phoenix', 'Arizona', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/73.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (74, 'Herrick', 'Aspland', 'Male', 'haspland21@addtoany.com', '6167409908', 'Grand Rapids', 'Michigan', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/74.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (75, 'Yancy', 'Belfrage', 'Male', 'ybelfrage22@eepurl.com', '3371985707', 'Lafayette', 'Louisiana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/75.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (76, 'Locke', 'Dunkirk', 'Male', 'ldunkirk23@state.tx.us', '8505229646', 'Pensacola', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/76.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (77, 'Udale', 'Branscombe', 'Male', 'ubranscombe24@ucoz.com', '7651394353', 'Anderson', 'Indiana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/77.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (78, 'Karyn', 'Loidl', 'Female', 'kloidl25@de.vu', '4104893182', 'Baltimore', 'Maryland', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/78.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (79, 'Randell', 'Bowser', 'Male', 'rbowser26@newyorker.com', '5091702166', 'Spokane', 'Washington', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/79.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (80, 'Myrtle', 'Brixey', 'Female', 'mbrixey27@instagram.com', '5702112939', 'Wilkes Barre', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/80.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (81, 'Marylin', 'Versey', 'Female', 'mversey28@about.com', '7129587883', 'Sioux City', 'Iowa', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/81.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (82, 'Mersey', 'Corhard', 'Female', 'mcorhard29@columbia.edu', '4139764969', 'Springfield', 'Massachusetts', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/82.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (83, 'Darren', 'MacGhee', 'Male', 'dmacghee2a@nbcnews.com', '4128567901', 'Mc Keesport', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/83.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (84, 'Irwinn', 'Poytress', 'Male', 'ipoytress2b@w3.org', '2024335448', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/84.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (85, 'Joyce', 'Blandford', 'Female', 'jblandford2c@java.com', '2137313435', 'Los Angeles', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/85.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (86, 'Domini', 'Marris', 'Female', 'dmarris2d@bravesites.com', '7132150398', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/86.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (87, 'Chad', 'Tenant', 'Female', 'ctenant2e@webnode.com', '6269378564', 'Pasadena', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/87.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (88, 'Aigneis', 'Mein', 'Female', 'amein2f@intel.com', '3372356432', 'Lafayette', 'Louisiana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/88.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (89, 'Teodoro', 'Overlow', 'Male', 'toverlow2g@dedecms.com', '2029613527', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/89.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (90, 'Helen', 'Kenen', 'Female', 'hkenen2h@amazon.co.jp', '8014785078', 'Salt Lake City', 'Utah', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/90.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (91, 'Melisenda', 'Dalrymple', 'Female', 'mdalrymple2i@china.com.cn', '9529848044', 'Young America', 'Minnesota', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/91.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (92, 'Torry', 'Maides', 'Male', 'tmaides2j@e-recht24.de', '3049841159', 'Charleston', 'West Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/92.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (93, 'Chiarra', 'Enden', 'Female', 'cenden2k@fotki.com', '7705862411', 'Atlanta', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/93.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (94, 'Estele', 'Shewon', 'Female', 'eshewon2l@engadget.com', '4056537068', 'Edmond', 'Oklahoma', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/94.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (95, 'Karlyn', 'Hellard', 'Female', 'khellard2m@ucoz.ru', '5164680400', 'New York City', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/95.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (96, 'Hedi', 'Macari', 'Female', 'hmacari2n@comsenz.com', '3219801665', 'Orlando', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/96.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (97, 'Erhart', 'Giovanetti', 'Male', 'egiovanetti2o@wunderground.com', '9156314881', 'El Paso', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/97.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (98, 'Georgi', 'Gwillyam', 'Male', 'ggwillyam2p@tmall.com', '6141305964', 'Columbus', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/98.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (99, 'Reggi', 'Cheke', 'Female', 'rcheke2q@dion.ne.jp', '9085206240', 'Elizabeth', 'New Jersey', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/99.jpg');
insert into contacts (id, firstname, lastname, gender, email, phone, city, state, country, picture) values (100, 'Marcus', 'Lequeux', 'Male', 'mlequeux2r@hud.gov', '5052589523', 'Albuquerque', 'New Mexico', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/100.jpg');
